# fly.toml app configuration file generated for curso-django-devpro on 2023-06-28T19:26:56-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "curso-django-devpro"
primary_region = "gru"
console_command = "/code/manage.py shell"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
