# Generated by Django 4.2.6 on 2023-10-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modulos", "0003_populando_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modulo",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
