# Generated by Django 4.2.6 on 2023-10-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modulos", "0005_aula"),
    ]

    operations = [
        migrations.AddField(
            model_name="aula",
            name="vimeo_id",
            field=models.CharField(default="1", max_length=32),
        ),
    ]
